BEGIN;
INSERT INTO clientes (nome, saldo) VALUES ('Cliente 1', 100.00);
UPDATE clientes SET saldo = saldo + 50 WHERE id = 1;
COMMIT;
BEGIN;
INSERT INTO clientes (nome, saldo) VALUES ('Cliente 2', 200.00);
UPDATE clientes SET saldo = saldo + 50 WHERE id = 2;
COMMIT;
BEGIN;
INSERT INTO clientes (nome, saldo) VALUES ('Cliente 3', 300.00);
UPDATE clientes SET saldo = saldo + 50 WHERE id = 2;
COMMIT;
BEGIN;
INSERT INTO clientes (nome, saldo) VALUES ('Cliente 4', 400.00);
UPDATE clientes SET saldo = saldo + 50 WHERE id = 3;
BEGIN;
INSERT INTO clientes (nome, saldo) VALUES ('Cliente 6', 600.00); 
DELETE FROM clientes WHERE id = 3;